config/routes.rb
Rails.application.routes.draw do
  get 'search/index'
  root 'search#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :categories do
    get :copy_filters_prompt, on: :member
    post :copy_filters, on: :member
    resources :category_filters_mappings
  end
  resources :category_filters do
    resources :dictionary_filter_values
  end
  # For now they all lead to one place but this approach makes it easier to split them into unique controllers later on
  resources :category_filters_boolean_filters, controller: :category_filters
  resources :category_filters_integer_filters, controller: :category_filters
  resources :category_filters_decimal_filters, controller: :category_filters
  resources :category_filters_string_filters, controller: :category_filters
  resources :category_filters_dictionary_filters, controller: :category_filters

  resources :products do
    resources :product_attributes, only: [:index, :edit, :update]
    resources :product_attributes_boolean_attributes, controller: :product_attributes
    resources :product_attributes_integer_attributes, controller: :product_attributes
    resources :product_attributes_decimal_attributes, controller: :product_attributes
    resources :product_attributes_string_attributes, controller: :product_attributes
    resources :product_attributes_dictionary_attributes, controller: :product_attributes
  end
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  belongs_to :parent, class_name: 'Category', foreign_key: 'parent_category_id', optional: true
  has_many :children, class_name: 'Category', foreign_key: 'parent_category_id', dependent: :destroy
  has_many :category_filters_mappings, dependent: :destroy
  has_many :category_filters, through: :category_filters_mappings
  has_many :products

  scope :without_children, lambda {
                             joins('LEFT OUTER JOIN categories as children ON categories.id = children.parent_category_id')
                               .where(children: { id: nil })
                           }

  after_create :copy_parent_filters

  validates_length_of :name, minimum: 2

  #needed for copy_filters_from controller action
  attribute :copy_from_id

  def copy_parent_filters
    return unless parent # mozliwe z rootem

    self.category_filters = parent.category_filters
  end

  def copy_filters_from(category)
    lacking_filters = category.category_filters.where.not(id: category_filters.map(&:id))
    lacking_filters.each do |filter|
      category_filters.push(filter)
    end
  end

  # returns filters that should be searchable within a given category
  def search_filters
    return category_filters if tree_end?

    reload
    end_nodes = all_children.filter(&:tree_end?)
    common_filters_in_categories(end_nodes)
  end

  def tree_end?
    reload
    children.empty?
  end

  def parent_filters
    return CategoryFilters.none unless parent

    parent.category_filters
  end

  # unlike just children, this one goes down the entire tree
  def all_children
    reload
    nodes = []
    queue = children.to_a
    until queue.empty?
      node = queue.pop
      nodes.push(node)
      queue += node.children.to_a
      queue.flatten!
    end
    nodes
  end

  private

  def common_filters_in_categories(categories)
    categories_filters = categories.map(&:search_filters)
    categories_filters.inject(:&) # intersection between N arrays
  end
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy, :copy_filters_prompt, :copy_filters]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  def copy_filters_prompt
    parent = @category.parent
    unless parent
      redirect_to category_path(@category), notice: 'This is a root category, it cant have any copied attributes'
      return
    end
    @candidates = parent.children.where.not(id: @category.id).map { |c| [c.name, c.id] }
  end

  def copy_filters
    to_copy_from = Category.find_by(id: category_params[:copy_from_id])
    redirect_to root_path and return unless to_copy_from # simplified error checking, just to show it's there
    @category.copy_filters_from(to_copy_from)
    redirect_to category_category_filters_mappings_path(@category), notice: 'Filters have been copied'
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def category_params
    params.require(:category).permit(:name, :parent_category_id, :copy_from_id)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :parent_category_id %>
    <%= form.number_field :parent_category_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/copy_filters_prompt.html.erb
<%= form_for :category, url: copy_filters_category_path(@category) do |form| %>
  <div class="field">
    <%= form.label :copy_from_id %>
    <%= form.select :copy_from_id, @candidates %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Parent category</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.parent.try(&:name) || 'No parent' %></td>
        <td><%= link_to 'Manage filters', category_category_filters_mappings_path(category) %></td>
        <td><%= link_to 'Copy filters from sibling', copy_filters_prompt_category_path(category) %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Parent category:</strong>
  <%= @category.parent_category_id %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>