config/routes.rb
Rails.application.routes.draw do
  get 'search/index'
  root 'search#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :categories do
    get :copy_filters_prompt, on: :member
    post :copy_filters, on: :member
    resources :category_filters_mappings
  end
  resources :category_filters do
    resources :dictionary_filter_values
  end
  # For now they all lead to one place but this approach makes it easier to split them into unique controllers later on
  resources :category_filters_boolean_filters, controller: :category_filters
  resources :category_filters_integer_filters, controller: :category_filters
  resources :category_filters_decimal_filters, controller: :category_filters
  resources :category_filters_string_filters, controller: :category_filters
  resources :category_filters_dictionary_filters, controller: :category_filters

  resources :products do
    resources :product_attributes, only: [:index, :edit, :update]
    resources :product_attributes_boolean_attributes, controller: :product_attributes
    resources :product_attributes_integer_attributes, controller: :product_attributes
    resources :product_attributes_decimal_attributes, controller: :product_attributes
    resources :product_attributes_string_attributes, controller: :product_attributes
    resources :product_attributes_dictionary_attributes, controller: :product_attributes
  end
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  belongs_to :category
  has_many :product_attributes, dependent: :destroy
  validate :category_must_have_no_children
  after_save :destroy_excessive_attributes, :build_lacking_attributes

  private

  def category_must_have_no_children
    return unless category
    return if category.tree_end?

    errors.add(:category, 'must have no further children (end of the tree)')
  end

  def build_lacking_attributes
    category.category_filters.each do |filter|
      next if product_attributes.exists?(category_filter: filter)

      prod_attr = filter.attribute_type.new
      prod_attr.category_filter = filter
      prod_attr.product = self
      prod_attr.save!
    end
  end

  # important when moving a product to a different category
  def destroy_excessive_attributes
    valid_filters_ids = category.category_filters.map(&:id)
    product_attributes.where.not(category_filter_id: valid_filters_ids).each(&:destroy)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def product_params
    params.require(:product).permit(:name, :category_id)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  # returns category name with all parents up to root, eg. "root -> cars -> bmw"
  def category_title_to_root(category)
    current_node = category
    str = +"#{current_node.name}"
    current_node = current_node.parent
    until current_node.nil?
      str = "#{current_node.name} ->" + str
      current_node = current_node.parent
    end
    str
  end

  def end_categories_with_name
    Category.without_children.map { |c| [category_title_to_root(c), c.id] }
  end
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :category_id %>
    <%= form.select :category_id, end_categories_with_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Category</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= category_title_to_root(product.category) %></td>
        <td><%= link_to 'Edit attributes', product_product_attributes_path(product) %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= category_title_to_root(@product.category) %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>