config/routes.rb
Rails.application.routes.draw do
  get 'search/index'
  root 'search#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :categories do
    get :copy_filters_prompt, on: :member
    post :copy_filters, on: :member
    resources :category_filters_mappings
  end
  resources :category_filters do
    resources :dictionary_filter_values
  end
  # For now they all lead to one place but this approach makes it easier to split them into unique controllers later on
  resources :category_filters_boolean_filters, controller: :category_filters
  resources :category_filters_integer_filters, controller: :category_filters
  resources :category_filters_decimal_filters, controller: :category_filters
  resources :category_filters_string_filters, controller: :category_filters
  resources :category_filters_dictionary_filters, controller: :category_filters

  resources :products do
    resources :product_attributes, only: [:index, :edit, :update]
    resources :product_attributes_boolean_attributes, controller: :product_attributes
    resources :product_attributes_integer_attributes, controller: :product_attributes
    resources :product_attributes_decimal_attributes, controller: :product_attributes
    resources :product_attributes_string_attributes, controller: :product_attributes
    resources :product_attributes_dictionary_attributes, controller: :product_attributes
  end
end

app/models/dictionary_filter_value.rb
class DictionaryFilterValue < ApplicationRecord
  belongs_to :category_filter
  validate :assigned_filter_must_be_dictionary_filter

  private

  def assigned_filter_must_be_dictionary_filter
    return if category_filter.type == 'CategoryFilters::DictionaryFilter'

    errors.add(:category_filter, 'must be a dictionary filter')
  end
end

app/controllers/dictionary_filter_values_controller.rb
class DictionaryFilterValuesController < ApplicationController
  before_action :set_category_filter
  before_action :set_dictionary_filter_value, only: [:show, :edit, :update, :destroy]

  def index
    @dictionary_filter_values = DictionaryFilterValue.where(category_filter: @category_filter)
  end

  def new
    @dictionary_filter_value = DictionaryFilterValue.new(category_filter: @category_filter)
    @url = category_filter_dictionary_filter_values_path
  end

  def show
  end

  def edit
    @url = category_filter_dictionary_filter_value_path(@category_filter, @dictionary_filter_value)
  end

  def create
    @dictionary_filter_value = DictionaryFilterValue.new(dictionary_params)
    @dictionary_filter_value.category_filter = @category_filter
    if @dictionary_filter_value.save
      redirect_to category_filter_dictionary_filter_value_path(@category_filter, @dictionary_filter_value)
    else
      render :new
    end
  end

  def update
    if @dictionary_filter_value.update(dictionary_params)
      redirect_to category_filter_dictionary_filter_value_path(@category_filter, @dictionary_filter_value)
    else
      render :edit
    end
  end

  def destroy
    @dictionary_filter_value.destroy
    redirect_to category_filter_dictionary_filter_values_path(@category_filter), notice: 'Dictionary value was successfully destroyed.'
  end

  private

  def set_category_filter
    @category_filter = CategoryFilter.find(params[:category_filter_id])
  end

  def set_dictionary_filter_value
    @dictionary_filter_value = DictionaryFilterValue.find(params[:id])
  end

  def dictionary_params
    params.require(:dictionary_filter_value).permit(:name)
  end
end

app/views/dictionary_filter_values/_form.html.erb
<%= form_for [@category_filter, @dictionary_filter_value], url: @url do |form| %>

  <% if @dictionary_filter_value.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dictionary_filter_value.errors.count, "error") %> prohibited this category_filter from being saved:</h2>

      <ul>
        <% @dictionary_filter_value.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/dictionary_filter_values/edit.html.erb
<h1>Edit Dictionary Value</h1>

<%= render 'form' %>

<%= link_to 'Back', category_filters_dictionary_filters_path(category_filter_id: @category_filter.id) %>

app/views/dictionary_filter_values/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Dictionary Filter Value</h1>

<table class="table table-bordered">
  <thead>
  <tr>
    <th>Value</th>
    <th>Category Filter</th>
    <th colspan=3"></th>
  </tr>
  </thead>

  <tbody>
  <% @dictionary_filter_values.each do |dictionary_filter_value| %>
    <tr>
      <td><%= dictionary_filter_value.name %></td>
      <td><%= link_to "#{dictionary_filter_value.category_filter.name}", category_filter_path(dictionary_filter_value.category_filter) %></td>
      <td><%= link_to 'Show', category_filter_dictionary_filter_value_path(@category_filter, dictionary_filter_value) %></td>
      <td><%= link_to 'Edit', edit_category_filter_dictionary_filter_value_path(@category_filter, dictionary_filter_value) %></td>
      <td><%= link_to 'Destroy', category_filter_dictionary_filter_value_path(@category_filter, dictionary_filter_value), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<br/>
<%= link_to 'New Dictionary Filter Value', new_category_filter_dictionary_filter_value_path(@category_filter) %>

app/views/dictionary_filter_values/new.html.erb
<h1>New Dictionary Value</h1>

<%= render 'form' %>

<%= link_to 'Back', category_filter_dictionary_filter_values_path(category_filter_id: @category_filter.id) %>

app/views/dictionary_filter_values/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category Filter:</strong>
  <%= @category_filter.name %>
</p>

<p>
  <strong>Value:</strong>
  <%= @dictionary_filter_value.name %>
</p>

<%= link_to 'Edit', edit_category_filter_dictionary_filter_value_path(@category_filter, @dictionary_filter_value) %> |
<%= link_to 'Back', category_filter_dictionary_filter_values_path(category_filter_id: @category_filter.id) %>