config/routes.rb
Rails.application.routes.draw do
  get 'search/index'
  root 'search#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :categories do
    get :copy_filters_prompt, on: :member
    post :copy_filters, on: :member
    resources :category_filters_mappings
  end
  resources :category_filters do
    resources :dictionary_filter_values
  end
  # For now they all lead to one place but this approach makes it easier to split them into unique controllers later on
  resources :category_filters_boolean_filters, controller: :category_filters
  resources :category_filters_integer_filters, controller: :category_filters
  resources :category_filters_decimal_filters, controller: :category_filters
  resources :category_filters_string_filters, controller: :category_filters
  resources :category_filters_dictionary_filters, controller: :category_filters

  resources :products do
    resources :product_attributes, only: [:index, :edit, :update]
    resources :product_attributes_boolean_attributes, controller: :product_attributes
    resources :product_attributes_integer_attributes, controller: :product_attributes
    resources :product_attributes_decimal_attributes, controller: :product_attributes
    resources :product_attributes_string_attributes, controller: :product_attributes
    resources :product_attributes_dictionary_attributes, controller: :product_attributes
  end
end

app/models/category_filter.rb
# frozen_string_literal: true

class CategoryFilter < ApplicationRecord
  include FormUsableConcern
  has_many :category_filters_mappings, dependent: :destroy
  has_many :categories, through: :category_filters_mappings
  has_many :product_attributes, dependent: :destroy

  validate :type_cannot_be_changed

  validates_length_of :name, minimum: 2



  private

  def type_cannot_be_changed
    errors.add(:type, 'Change of type is not allowed!') if type_changed? && persisted?
  end


end

app/models/category_filters/boolean_filter.rb
module CategoryFilters
  class BooleanFilter < CategoryFilter
    def attribute_type
      ProductAttributes::BooleanAttribute
    end

    def field_type_in_form
      'check_box'
    end

  end
end

app/models/category_filters/decimal_filter.rb
module CategoryFilters
  class DecimalFilter < CategoryFilter
    def attribute_type
      ProductAttributes::DecimalAttribute
    end

    def field_type_in_form
      'number_field'
    end
  end
end

app/models/category_filters/dicionary_filter.rb
module CategoryFilters
  class DictionaryFilter < CategoryFilter

  end
end

app/models/category_filters/dictionary_filter.rb
module CategoryFilters
  class DictionaryFilter < CategoryFilter
    has_many :dictionary_filter_values, class_name: 'DictionaryFilterValue', foreign_key: 'category_filter_id', dependent: :destroy

    def available_values
      dictionary_filter_values.map(&:name)
    end

    def attribute_type
      ProductAttributes::DictionaryAttribute
    end

    def field_type_in_form
      'select'
    end

    def extra_fields_in_form
      [available_values]
    end

  end
end

app/models/category_filters/integer_filter.rb
module CategoryFilters
  class IntegerFilter < CategoryFilter
    def attribute_type
      ProductAttributes::IntegerAttribute
    end

    def field_type_in_form
      'number_field'
    end
  end

end

app/models/category_filters/string_filter.rb
module CategoryFilters
  class StringFilter < CategoryFilter
    def attribute_type
      ProductAttributes::StringAttribute
    end
  end

end

app/controllers/category_filters_controller.rb
class CategoryFiltersController < ApplicationController
  before_action :set_category_filter, only: [:show, :edit, :update, :destroy]

  # GET /category_filters
  # GET /category_filters.json
  def index
    @category_filters = CategoryFilter.all
  end

  # GET /category_filters/1
  # GET /category_filters/1.json
  def show
  end

  # GET /category_filters/new
  def new
    @category_filter = CategoryFilter.new
  end

  # GET /category_filters/1/edit
  def edit
  end

  # POST /category_filters
  # POST /category_filters.json
  def create
    @category_filter = CategoryFilter.new(category_filter_params)

    respond_to do |format|
      if @category_filter.save
        format.html { redirect_to @category_filter, notice: 'Category filter was successfully created.' }
        format.json { render :show, status: :created, location: @category_filter }
      else
        format.html { render :new }
        format.json { render json: @category_filter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /category_filters/1
  # PATCH/PUT /category_filters/1.json
  def update
    respond_to do |format|
      if @category_filter.update(category_filter_params)
        format.html { redirect_to @category_filter, notice: 'Category filter was successfully updated.' }
        format.json { render :show, status: :ok, location: @category_filter }
      else
        format.html { render :edit }
        format.json { render json: @category_filter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /category_filters/1
  # DELETE /category_filters/1.json
  def destroy
    @category_filter.destroy
    respond_to do |format|
      format.html { redirect_to category_filters_url, notice: 'Category filter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category_filter
    @category_filter = CategoryFilter.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def category_filter_params
    params.require(:category_filter).permit(:name, :type)
  end
end

app/helpers/category_filters_helper.rb
module CategoryFiltersHelper
end

app/views/category_filters/_form.html.erb
<%= form_for(@category_filter, as: :category_filter, local: true) do |form| %>
  <% if category_filter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category_filter.errors.count, "error") %> prohibited this category_filter from being saved:</h2>

      <ul>
      <% category_filter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :type %>
    <%= form.select :type, CategoryFilter.descendants.map(&:name) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/category_filters/edit.html.erb
<h1>Editing Category Filter</h1>

<%= render 'form', category_filter: @category_filter %>

<%= link_to 'Show', @category_filter %> |
<%= link_to 'Back', category_filters_path %>

app/views/category_filters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Category Filters</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @category_filters.each do |category_filter| %>
      <tr>
        <td><%= category_filter.name %></td>
        <td><%= category_filter.type %></td>
        <td>
          <% if category_filter.type.to_s == 'CategoryFilters::DictionaryFilter' %>
            <%= link_to 'Edit dictionary values', category_filter_dictionary_filter_values_path(category_filter) %>
          <% end %>
        </td>
        <td><%= link_to 'Show', category_filter %></td>
        <td><%= link_to 'Edit', edit_category_filter_path(category_filter) %></td>
        <td><%= link_to 'Destroy', category_filter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category Filter', new_category_filter_path %>

app/views/category_filters/new.html.erb
<h1>New Category Filter</h1>

<%= render 'form', category_filter: @category_filter %>

<%= link_to 'Back', category_filters_path %>

app/views/category_filters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category_filter.name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @category_filter.type %>
</p>

<%= link_to 'Edit', edit_category_filter_path(@category_filter) %> |
<%= link_to 'Back', category_filters_path %>